import type { Metadata } from "next";
import { Playfair_Display, Poppins } from "next/font/google";
import "./globals.css";
import { CookieBanner } from "@/components/logic/cookie-banner";
import { ConsentProvider } from "@/components/logic/providers/consent-provider";
import { GoogleTagManager } from "@/components/logic/google-tag-manager";
import { Header } from "@/components/ui/header";
import { Footer } from "@/components/ui/footer";

const poppins = Poppins({
  variable: "--font-primary",
  weight: "400",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-secondary",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplay.variable} ${poppins.variable} antialiased text-lg`}
      >
        <Header />
        <ConsentProvider>
          {children}
          <CookieBanner />
          <GoogleTagManager />
        </ConsentProvider>
        <Footer />
      </body>
    </html>
  );
}
